### PR TITLE
Update geo dependency

### PR DESCRIPTION
**Pull request by tapajos**
## Why

We have another library that depends of geo ~> 2.0. tz_world is working as expected with geo ~> 2.0.

## Release

The latest version (0.1.0) published in hex still using PostGIS. Master is performing better for us than the released version.

Do you have any plan to release a new version anytime soon?

#### released version
```
Name                    ips        average  deviation         median         99th %
function         21.28       47.00 ms    ±10.66%       46.20 ms       69.57 ms
```
#### master
```
Name                    ips        average  deviation         median         99th %
 function         53.15       18.81 ms    ±19.75%       17.62 ms       31.48 ms
```

### CODE REVIEW

**Comment by kipcole9** [comment]
@kimlai I notice there hasn't been a lot of active maintenance and wonder if this is still an active project for you?  It would be great if you could publish master to hex since this non-GIS version is most helpful. And to relax the `geo` dependencies to allow `geo` version 2.0 and 3.0 both of which appear to work fine.

**Comment by kimlai** [comment]
Sorry I completely missed this pull request.

> wonder if this is still an active project for you?

It is not, I don't use it in production anymore.

I'll do my best to publish to Hex before the end of the week. Are you using this in production?

**Comment by tapajos** [comment]
Yes, I'm still using that in production.

**Comment by kipcole9** [comment]
I have forked and will work on:
1. Scripting a way to update the timezone boundary data
2. Updating the geo deps in mix.exs

And if that goes well over the weekend I may be interested to help with ongoing maintenance if that suits you.

**Comment by kimlai** [comment]
Looking back at the code, I think that we should get rid of the dependency. It made sense when the library was using PostgreSQL, to get the custom types from `geo_postgis`. But now, it seems that it is only used to get the `Geo.Point{}` struct, which seems a bit overkill.

What do you think?

> And if that goes well over the weekend I may be interested to help with ongoing maintenance if that suits you.

Yes I think that it would make sense.

**Comment by kipcole9** [comment]
I was thinking the same - however on diving into the source data there is now a GeoJson data source that may not have been there when you wrote this lib. And its awfully easy to download, JSON decode and then GeoJSON decode as well.

Therefore I think keeping the dependency might be worth it because it automates a lot of the data munging. And I think with minimal effort I can make the lookups use this source data format (which I would still save as binary terms for the packaging of course.

WDYT?

**Comment by kimlai** [comment]
@tapajos could you try the the version (0.2.0) and see if it works for you?

**Comment by kipcole9** [comment]
Closed in favour of the other PR and on the assumption the new release meets this requirement,.

**Pull request closed without merging**
